//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_VRControls : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean LeftBig
        {
            get
            {
                return SteamVR_Actions.vRControls_LeftBig;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftLittle
        {
            get
            {
                return SteamVR_Actions.vRControls_LeftLittle;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftB
        {
            get
            {
                return SteamVR_Actions.vRControls_LeftB;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftA
        {
            get
            {
                return SteamVR_Actions.vRControls_LeftA;
            }
        }
        
        public virtual SteamVR_Action_Boolean RIghtBig
        {
            get
            {
                return SteamVR_Actions.vRControls_RIghtBig;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightLittle
        {
            get
            {
                return SteamVR_Actions.vRControls_RightLittle;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightA
        {
            get
            {
                return SteamVR_Actions.vRControls_RightA;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightB
        {
            get
            {
                return SteamVR_Actions.vRControls_RightB;
            }
        }
    }
}
